### ISSUE TITLE
Extend JMAP authentication process to support multiple iterations for additional auth factors

### ISSUE THREAD

**Issue by thomascube** [linagora/jmap-client#12]
The current implementation of `Client.authenticate()` from PR #10 only supports a 2-step authentication procedure while the JMAP protocol in fact describes n-steps. Once you have the continuation token, you can receive subsequent HTTP 200 responses until the authentication is complete.

From the [JMAP spec](http://jmap.io/spec.html#getting-an-access-token) we read

> The server will then return one of the same set of responses as before, which should
> be handled the same (for example, if 2FA is required, a 200 response may be returned
> again and a second password prompted for, with a prompt text explaining to the user
> that a one-time password has been SMSed to them).

**Comment by ddolcimascolo** [comment]
Agreed, and this should be fairly easy to support using our `Promise`-based authentication.

**Comment by thomas-hilaire** [comment]
Closed, see #27
