### ISSUE TITLE
Expose hasMail, hasCalendars, and capabilities

### ISSUE THREAD

**Issue by adityab** [linagora/jmap-client#13]
According to the spec, a JMAP Account has the following boolean properties:

`hasMail`, `hasContacts`, and `hasCalendars, and in addition`capabilities`, which I believe is supposed to be an object containing boolean feature flags.

The library should expose at least the first three, and ideally also the last one. For Roundcube Next, I want to use this response as a way to dynamically load only the features that the administrators have enabled for any given user.

I was hoping to find these in the `Account` model, but it isn't there - am I looking in the wrong place by any chance? If not, I'll send a pull request soon. Cheers. :)

**Comment by thomas-hilaire** [comment]
Hello,

We've started to work on the email side only, so we haven't managed these properties.
Of course these flags should belong to the Account model.

Thanks you to plan such pull-request, cheers!

**Comment by thomascube** [comment]
FYI: the JMAP spec has recently changed and now describes account capabilities as individual objects of types `AccountCapabilities`, `MailCapabilities`, `ContactsCapabilities` and `CalendarsCapabilities`. See http://jmap.io/spec.html#accounts-1 and the according [forum thread].(https://groups.google.com/forum/#!topic/jmap-discuss/S6HJ4yiEvN8)

**Comment by ddolcimascolo** [comment]
Thanks @thomascube, we indeed need to implement this new stuff :)
