### ISSUE TITLE
Expose transport and JMAP errors

### ISSUE THREAD

**Issue by thomascube** [linagora/jmap-client#18]
The handling of HTTP transport errors, mainly from within the `JQueryTransport` class is kept a bit too simple. It only rejects the promise with a simple `Error` instance reflecting the error in the message string.

For a JMAP application it's necessary to distinguish different errors (network, authentication, forbidden, etc.) in order to act accordingly. Therefore we should introduce a `TransportError` class which at least exposes the HTTP response status.

The JMAP protocol itself specifies error responses for individual commands. These should be encapsulated into `JmapError` objects holding the `type` property from the response as well as the `command` initially sent.

**Comment by ddolcimascolo** [comment]
You're absolutely right.
To be really honest, error handling has been kept very basic in the current implementation so as to get a working library on tracks quickly. A "proof" of this is the first item of the roadmap in the [README](/linagora/jmap-client/blob/master/README.md#roadmap) :)

Anyway, I agree on the `TransportError` class exposing the HTTP status code and at least an error message (_timeout_, _connection refused_, etc.) and also on the `JmapError` class, though its prototype should be more precisely defined when someone starts working on this issue.
