### ISSUE TITLE
Automatically deploy the latest build from master branch

### ISSUE THREAD

**Issue by sngo25** [linagora/jmap-client#30]
Currently, we just have release branches so there is no way to use latest version from master branch with the package management like NPM or Bower. It's nice to have a branch named `release-latest` automatically deployed by Travis when there is a success build from master branch.

Ref: http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

**Comment by ddolcimascolo** [comment]
We won't do it. I don't want _master_ built artifacts to be checked-in in the repo.

We might consider having a separated repo for generated files, but that is another story.

**Comment by kewisch** [comment]
I believe you can npm install directly from a git repository by specifying it in a special format in package.json, so no need to publish a branch for this.
