### ISSUE TITLE
Adapt AuthAccess model to new JMAP endpoint properties

### ISSUE THREAD

**Issue by thomascube** [linagora/jmap-client#38]
Apparently the JMAP spec [recently changed](https://github.com/jmapio/jmap/commit/f99391f) the [authentication complete response](http://jmap.io/spec.html#authentication-is-complete-access-token-created) to use an "Url" suffix for URL properties. Therefore the according model should be adapted to keep up with the spec.

**Comment by ddolcimascolo** [comment]
Right Thomas, thx for reporting.
Are you willing to submit a PR for this?

**Comment by thomascube** [comment]
Yes, I can take that but it may take a few days until I find time to do it. I just created the issue first in order to not forget about it :-)

**Comment by thomascube** [comment]
The latest JMAP spec also lists additional properties for the `AuthAccess` model: _username_, _versions_, _extenstions_. Should these become required properties as well? Or shall we keep them optional for better backwards compatibility?

**Comment by thomascube** [comment]
Personally, I'd make _username_ mandatory and treat _versions_ and _extensions_ optionally as they likely are empty anyways.

**Comment by ddolcimascolo** [comment]
Yeah, I'm OK with your suggestion.

**Comment by thomas-hilaire** [comment]
Fixed by #41
