### ISSUE TITLE
Refactor Auth-related code as per the latest spec

### ISSUE THREAD

**Issue by ddolcimascolo** [linagora/jmap-client#44]
Relevant changes: https://groups.google.com/forum/#!topic/jmap-discuss/mgXsDqzPR6Y
Commits in the spec:
- https://github.com/jmapio/jmap/commit/785f4c76153fdab79e25c5a653a8f1d3a723e1f7
- https://github.com/jmapio/jmap/commit/aa56257d58744d5321f8e2324c1468e984a5938b
- https://github.com/jmapio/jmap/commit/7e7a9e3d753cdb7d75d83c719514bf4781e059c8
- https://github.com/jmapio/jmap/commit/05d82a81002ac5baca901beb6a0e68a227e1c197

**Comment by thomascube** [comment]
I'm working on it...

**Comment by thomascube** [comment]
Client behavior related to specific HTTP status codes requires #18 to be done first. I suggest to extract these into a follow-up ticket.
